// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'post_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************
//
// This file is automatically generated by running:
// flutter pub run build_runner build
//
// Important concepts:
// 1. This file maps between JSON keys and Dart fields
// 2. It handles null safety and type conversions
// 3. You should NOT manually edit this file - run the build_runner command

/// Generated function to create a PostModel from a JSON map
///
/// This is what json_serializable generates under the hood.
/// Understanding this helps you debug when serialization fails.
PostModel _$PostModelFromJson(Map<String, dynamic> json) {
  return PostModel(
    // Each field is extracted from the JSON map
    // 'as int' performs type casting - fails if type is wrong
    userId: json['userId'] as int,
    id: json['id'] as int,
    title: json['title'] as String,
    body: json['body'] as String,
  );
}

/// Generated function to convert a PostModel to a JSON map
///
/// Used when sending data to the server (POST/PUT requests)
Map<String, dynamic> _$PostModelToJson(PostModel instance) {
  return <String, dynamic>{
    'userId': instance.userId,
    'id': instance.id,
    'title': instance.title,
    'body': instance.body,
  };
}
