import 'package:json_annotation/json_annotation.dart';

/// ============================================================================
/// هذا الملف يوضح تسلسل/فك تسلسل JSON في Dart
/// JSON Serialization/Deserialization in Dart
/// ============================================================================
///
/// تسلسل JSON مهم جداً لتحويل استجابات API إلى كائنات Dart
/// JSON serialization is crucial for converting API responses into Dart objects.
///
/// المفاهيم الأساسية | Key Concepts:
/// 1. @JsonSerializable() - تخبر Dart بتوليد كود التسلسل تلقائياً
///    Annotation that tells Dart to generate serialization code
/// 2. fromJson() - منشئ يحول خريطة JSON إلى كائن Dart
///    Constructor that converts JSON map to Dart object
/// 3. toJson() - دالة تحول كائن Dart إلى خريطة JSON
///    Method that converts Dart object to JSON map
///
/// في مشروع حقيقي، ستشغل الأمر: flutter pub run build_runner build
/// In a real project, you would run: flutter pub run build_runner build
/// هذا يولد ملف '.g.dart' تلقائياً | This generates the '.g.dart' file automatically.

// هذا يخبر مولد الكود بتوليد كود لهذا الكلاس
// This tells the code generator to generate code for this class
part 'post_model.g.dart';

/// ============================================================================
/// كلاس PostModel - نموذج يمثل منشور من REST API
/// A model class representing a blog post from a REST API
/// ============================================================================
///
/// هذا يوضح كيفية هيكلة النماذج لاستجابات API
/// This demonstrates how to structure models for API responses
///
/// مثال JSON من API:
/// Example JSON from API:
/// ```json
/// {
///   "userId": 1,
///   "id": 1,
///   "title": "sunt aut facere repellat",
///   "body": "quia et suscipit..."
/// }
/// ```
@JsonSerializable()
class PostModel {
  // هذه الحقول تطابق مفاتيح JSON من استجابة API
  // These fields correspond to JSON keys from the API response
  // نستخدم @JsonKey إذا كان اسم مفتاح JSON مختلف عن اسم الحقل
  // The @JsonKey annotation is used if the JSON key differs from the field name

  /// معرف المستخدم الذي أنشأ هذا المنشور
  /// The ID of the user who created this post
  /// في تطبيق حقيقي، قد يشير هذا إلى نموذج User
  /// In a real app, this might reference a User model
  final int userId;

  /// المعرف الفريد لهذا المنشور
  /// Unique identifier for this post
  /// يُستخدم لعمليات مثل UPDATE و DELETE
  /// Used for operations like UPDATE and DELETE
  final int id;

  /// عنوان المنشور - يُستخدم في واجهة المستخدم للعرض
  /// The title of the post - Used in UI for display
  final String title;

  /// المحتوى الرئيسي للمنشور - عادة نص طويل
  /// The main content/body of the post - Typically longer text content
  final String body;

  /// منشئ PostModel - جميع الحقول مطلوبة
  /// Constructor for PostModel - All fields are required in this example
  PostModel({
    required this.userId,
    required this.id,
    required this.title,
    required this.body,
  });

  /// ========================================
  /// Factory Constructor لفك تسلسل JSON
  /// Factory constructor for JSON deserialization
  /// ========================================
  ///
  /// هذا يُنشأ بواسطة مولد الكود (json_serializable)
  /// This is generated by the code generator (json_serializable)
  /// لكنه موضح هنا للأغراض التعليمية
  /// But shown here for educational purposes
  ///
  /// كيف يعمل | How it works:
  /// - يأخذ خريطة JSON من استجابة API
  ///   Takes a JSON map from the API response
  /// - يربط مفاتيح JSON بحقول كائن Dart
  ///   Maps JSON keys to Dart object fields
  /// - يرجع نسخة جديدة من PostModel
  ///   Returns a new PostModel instance
  factory PostModel.fromJson(Map<String, dynamic> json) =>
      _$PostModelFromJson(json);

  /// ========================================
  /// تحويل هذا PostModel إلى خريطة JSON
  /// Converts this PostModel instance to a JSON map
  /// ========================================
  ///
  /// هذا يُنشأ بواسطة مولد الكود (json_serializable)
  /// This is generated by the code generator (json_serializable)
  ///
  /// يُستخدم عند | Used when:
  /// - إرسال طلبات POST/PUT إلى API
  ///   Sending POST/PUT requests to the API
  /// - الحفظ في التخزين المحلي
  ///   Saving to local storage
  /// - تمرير البيانات بين الشاشات
  ///   Passing data between screens
  Map<String, dynamic> toJson() => _$PostModelToJson(this);

  /// خاصية محسوبة - مفيدة لمنطق عرض واجهة المستخدم
  /// Example of a computed property - Often useful for UI display logic
  String get preview {
    return '$title\nBy User: $userId';
  }

  /// تجاوز toString للتصحيح - يعرض جميع الحقول بتنسيق قابل للقراءة
  /// Override toString for debugging - Shows all fields in a readable format
  @override
  String toString() =>
      'PostModel(userId: $userId, id: $id, title: $title, body: $body)';

  /// ========================================
  /// نمط copyWith - للنسخ مع تغييرات
  /// copyWith pattern - for copying with changes
  /// ========================================
  ///
  /// مفيد عندما تحتاج لتحديث حقول معينة مع الحفاظ على الحقول الأخرى
  /// Useful when you need to update specific fields but keep other fields the same
  /// هذا يتبع نمط الثبات (immutability pattern)
  /// This follows the immutability pattern
  PostModel copyWith({int? userId, int? id, String? title, String? body}) {
    return PostModel(
      userId: userId ?? this.userId,
      id: id ?? this.id,
      title: title ?? this.title,
      body: body ?? this.body,
    );
  }
}
